on:
  push:
    branches:
      - 'main'

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror SOURCE to DEST
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'main'
        dest: 'master'
